name: iOS starter workflow
on: [push,workflow_dispatch]
jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    steps: 
        - name: "greet user"
          run: echo "hello world!"
    
